/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchBatchIdRouteImport } from './routes/batch.$batchId'
import { Route as WatchBatchIdChildIdRouteImport } from './routes/watch.$batchId.$childId'
import { Route as SubjectBatchIdSubjectIdRouteImport } from './routes/subject.$batchId.$subjectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchBatchIdRoute = BatchBatchIdRouteImport.update({
  id: '/batch/$batchId',
  path: '/batch/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchBatchIdChildIdRoute = WatchBatchIdChildIdRouteImport.update({
  id: '/watch/$batchId/$childId',
  path: '/watch/$batchId/$childId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectBatchIdSubjectIdRoute = SubjectBatchIdSubjectIdRouteImport.update({
  id: '/subject/$batchId/$subjectId',
  path: '/subject/$batchId/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batch/$batchId': typeof BatchBatchIdRoute
  '/subject/$batchId/$subjectId': typeof SubjectBatchIdSubjectIdRoute
  '/watch/$batchId/$childId': typeof WatchBatchIdChildIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batch/$batchId': typeof BatchBatchIdRoute
  '/subject/$batchId/$subjectId': typeof SubjectBatchIdSubjectIdRoute
  '/watch/$batchId/$childId': typeof WatchBatchIdChildIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batch/$batchId': typeof BatchBatchIdRoute
  '/subject/$batchId/$subjectId': typeof SubjectBatchIdSubjectIdRoute
  '/watch/$batchId/$childId': typeof WatchBatchIdChildIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batch/$batchId'
    | '/subject/$batchId/$subjectId'
    | '/watch/$batchId/$childId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batch/$batchId'
    | '/subject/$batchId/$subjectId'
    | '/watch/$batchId/$childId'
  id:
    | '__root__'
    | '/'
    | '/batch/$batchId'
    | '/subject/$batchId/$subjectId'
    | '/watch/$batchId/$childId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchBatchIdRoute: typeof BatchBatchIdRoute
  SubjectBatchIdSubjectIdRoute: typeof SubjectBatchIdSubjectIdRoute
  WatchBatchIdChildIdRoute: typeof WatchBatchIdChildIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch/$batchId': {
      id: '/batch/$batchId'
      path: '/batch/$batchId'
      fullPath: '/batch/$batchId'
      preLoaderRoute: typeof BatchBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$batchId/$childId': {
      id: '/watch/$batchId/$childId'
      path: '/watch/$batchId/$childId'
      fullPath: '/watch/$batchId/$childId'
      preLoaderRoute: typeof WatchBatchIdChildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$batchId/$subjectId': {
      id: '/subject/$batchId/$subjectId'
      path: '/subject/$batchId/$subjectId'
      fullPath: '/subject/$batchId/$subjectId'
      preLoaderRoute: typeof SubjectBatchIdSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchBatchIdRoute: BatchBatchIdRoute,
  SubjectBatchIdSubjectIdRoute: SubjectBatchIdSubjectIdRoute,
  WatchBatchIdChildIdRoute: WatchBatchIdChildIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
